### ISSUE TITLE
Not exposed in HA integrations

### ISSUE THREAD

**Issue by dswarne** [StephanJoubert/home_assistant_solarman#4]
Hi,

Firstly thanks for the efforts, much appreciated.
Could you maybe assist me? I have successfully downloaded the integration in HACS and i can see it in the relevant dashboards and file system, however the plugin is not exposed in HA integrations when I search.

Am I missing something obvious or doing something wrong?

Kind Regards

**Comment by StephanJoubert** [comment]
Hi,

I think you are almost there. You can try the following:
1. Click on "Developer Tools" on the left, and under "States" view the entities.
2. Under "Filter Entities" type "inverter". If the system works correctly you should see a number of entities ex.sensor.deye_inverter_id (in my case I called the inverter deye, but it may differ depending on  your configuration)

The screen capture in the readme was created by adding a card "by entity", and under "Search Entities" I just filtered by typing the name "deye" and selected multiple entities. The name "deye" was pulled from my configuration and may be different depending on your configuration.

Hope you have success.

**Comment by dswarne** [comment]
Thanks for the feedback, I have however only downloaded the integration but can start it or even find the config to edit the ip address, I'm relatively new to custom plugins and I'm sure I've missed a step.

All i did was find the integration in HACS then click the download. cant figure out the next step.

**Comment by StephanJoubert** [comment]
You need only add a few steps:
1. You need to configure the router to give the inverter a fixed IP. This is important since the component will try to find the inverter at a specific IP.
2. Then get the serial number of the inverter-collector. The easiest way to do that is to open a browser and browse to the IP you specified above. The login with username "admin" and password "admin". On the web UI, under "Status" expand "Device information" and note the "Device serial number"
3. Then you need to add a few lines in the configuration.yaml file. There is a configurator that makes this relatively easy.

In that file, you just need to add an entry under "sensors" as follows:
sensors:
  - platform: solarman
    name: SUNSYNK <- you can change this to the brand of the inverter
    inverter_host: 192.168.0.201 <-- you need to change this to the IP you specified in step 1
    inverter_port: 8899
    inverter_serial: 1720747149 <-- change this to the serial number you got in step 2
    scan_interval: 30
4. Then restart Home Assistant to accept the changes.

**Comment by dswarne** [comment]
Thanks Bud,

All visible now, I made a noob error by "sensors" and not "sensor in the config

**Comment by xb385** [comment]
To add to this, i got all the entities showing but everything is set to "unknown" values
as far as i can tell everything is configured correctly

**Comment by Toma82** [comment]
I have the same problem in HA no entities are unknown 
![image](https://user-images.githubusercontent.com/81713401/151694204-c16cf47a-a42c-41f2-9333-8d7306307af0.png)

And in integration after I have the following error

![image](https://user-images.githubusercontent.com/81713401/151694240-22a379a0-19a3-4005-bb0f-977993749672.png)

**Comment by StephanJoubert** [comment]
The message trace refers to a different piece of code. A quick google seems to point to here: https://github.com/MichaluxPL/Sofar_LSW3

It may be that the two components influence each other so I would recommend disabling the Sofar_LSW3 code  just to see if it makes a difference.

The good news is that both the LSW3 integration and this component uses the same protocol, so if one of them works, the other one should also work.

**Comment by Toma82** [comment]
Well, unfortunately, despite the removal of that integration, I still have unknown entities
![image](https://user-images.githubusercontent.com/81713401/151695447-cbe761f1-f3b3-4644-95f4-accd81f287fd.png)

**Comment by xb385** [comment]
i still dont get a read out, where exactly can i see errors so i can try to bugfix?

**Comment by StephanJoubert** [comment]
You can look at the logs (Configuration | Settings | Logs) and click on "Load full home assistant logs" and see if you get any traces.

I have updated the readme.md file to help with installation. You can just go though that process as well to confirm that the configuration is correct. If the collector you have is incompatible, you can try the "Omnik Solar integration" that is newly added to HACS to see if that works.

**Comment by ianfretwell** [comment]
The example code incorrectly states that the config needs to go under 'sensors:'  as pointed out above, this should actually be 'sensor:'

Regardless of that I seem to have the same issue as @xb385 - the integration has brought all the sensors in but they are all marked as 'unknown' - although very, very occasionally I see two of them change to 'LOOKUP'

This integration works just fine though (I have it disabled whilst I am trying to get yours working) [https://github.com/robbinjanssen/home-assistant-omnik-inverter](url)
This also appears to be using v5 of the connection so I really can't see any reason why yours won't work. Any more ideas ?

**Comment by StephanJoubert** [comment]
Thanks for pointing me to the typo in the documentation - I have fixed and pushed that.

I had a look at the other integration, and from what I can gather it uses a different method to obtain the data. Rather than using the modbus interface, it queries it directly from the web JSON API. So it is stil possible that the version is incompatible.

Apart from the version of the protocol, we also have the mapping of parameter ids to actual parameters. Ex 00BD being Battery Status. I have verified that against the solarman app, but in case Omik has a different app it may use a  different mapping and be incompatible?

**Comment by donovanvdberg** [comment]
Hi All,  Anyone got this working with Firmware version LSW3_15_FFFF_1.0.65 ?
IP has been updated and set static and SN updated in config file. All Sensors are stating Unknown

**Comment by ianfretwell** [comment]
@StephanJoubert  I missed your point about Solarman app - yes, I can use this to see my details just fine - no issues there.

It looks like some of the figures are updating - but it's now at a consistent ten minute interval (not 30 seconds, which is what is in the config) : -

![image](https://user-images.githubusercontent.com/52041704/151781168-fe545afe-b205-4ec7-bf02-81986cdeda22.png)

**Comment by ianfretwell** [comment]
@StephanJoubert OK, many thanks anyway - it was worth a go!
